Remove Facebook copyrights, update licenses to MIT
acao/graphiql pull request #7
Opened 2019-06-11 15:27 UTC by acao

- remove copyright statements from all files
- update license files to MIT
- export LICENSE files from all projects
- update/add package.json license entries
- normalize import/require formatting across all files

2019-06-11 15:37 UTC, benjie commented on packages/graphql-language-service-parser/src/RuleHelpers.js
> +// These functions help build matching rules for ParseRules.
Should this comment be above the import?

2019-06-11 15:37 UTC, benjie commented on packages/graphql-language-service-parser/src/RuleHelpers.js
> +// These functions help build matching rules for ParseRules.
No.

2019-06-11 15:37 UTC, benjie commented on packages/graphql-language-service-parser/src/RuleHelpers.js
> +// These functions help build matching rules for ParseRules.
Ignore :)

2019-06-11 15:44 UTC, benjie requested changes
LGTM; just need to delete any remaining `PATENTS` files and then it's good to go up the chain for approval 👍

2019-06-11 16:10 UTC, acao commented
@benjie thanks !! all the `PATENTS` files are gone now

2019-06-11 16:13 UTC, benjie approved these changes
Need approval from GraphQL Foundation; but LGTM 👍

2019-06-11 16:16 UTC, benjie commented
@leebyron and @caniszczyk; please approve these license changes 👍

2019-06-12 00:16 UTC, caniszczyk commented
please don't remove copyright headers, just change attribution to "GraphQL Contributors"

2019-06-12 02:52 UTC, acao commented
@caniszczyk can do. I modelled this on Ivans PR you approved here:
 https://github.com/graphql/express-graphql/pull/515/files
Does this mean he needs to re-add the copyright headers? Or is it just different for these projects?

2019-06-12 05:56 UTC, acao commented
@caniszczyk was easier to just re-create the branch
https://github.com/acao/graphiql/pull/9

2019-06-12 05:57 UTC, closed without merging